# Generated by Django 4.2.5 on 2023-12-01 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tikect',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('email', models.CharField(max_length=120)),
                ('monumentId', models.IntegerField()),
                ('count', models.IntegerField()),
                ('price', models.IntegerField()),
                ('date', models.DateField()),
                ('shift', models.CharField(max_length=120)),
            ],
        ),
    ]
