# Generated by Django 4.2.5 on 2023-12-12 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_tikect_scanned_tikect_trasactionid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monuments',
            old_name='foreignPrice',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='monuments',
            old_name='indPrice',
            new_name='price',
        ),
        migrations.AddField(
            model_name='tikect',
            name='gender',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
